baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Elixier"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

# Enable comments by entering your Disqus shortname
disqusShortname = ""
googleAnalytics = ""
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination
hasCJKLanguage = true

[outputs]
#home = ["HTML", "RSS", "Algolia"]
home = ["HTML"]

[params]
  header_image = "img/home-img-3.jpg"
  SEOTitle = "Elixier Blog - Food Innovations Technologies Start-ups"
  description = "Food Innovations Technologies Start-ups"
  keyword = "Food Innovations Technologies Start-ups"
  slogan = "Food Innovations Technologies Startups"

  image_404 = "img/404-bg.jpg"
  title_404 = ""
  omit_categories = false

  # leancloud storage for page view counter
  page_view_conter = false 
  leancloud_app_id = ""
  leancloud_app_key = ""

  # algolia site search
  algolia_search = false
  algolia_appId = ""
  algolia_indexName = ""
  algolia_apiKey = ""

  # Sidebar settings
  sidebar_about_description = "Food Scientist, R&D professional"
  sidebar_avatar = "img/_20150118_215047.JPG"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = false 
  featured_condition_size = 1 

  # Baidu Analytics
  ba_track_id = ""
  
  # We need a proxy to access Disqus api in China
  # Follow https://github.com/zhaohuabing/disqus-php-api to set up your own disqus proxy
  disqus_proxy = ""
  disqus_site = ""

  #Enable wechat pay & alipay to allow readers send reward money if they like the articles 
  reward = true 
  # reward_guide = "" 

  friends = false
  bookmarks = false
  about_me = true

  # Include any custom CSS and/or JS files, url or relative to /static folder
  #custom_css = ["css/lightbox.css", "https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css", "css/main.css"]
  #custom_js = ["js/lightbox.js", "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js", "js/main.js"]

  [params.social]
  rss            = false 
  email          = "techgrs29@gmail.com"
  facebook       = ""
  linkedin       = "https://www.linkedin.com/in/gauri-sawant-84867450"
  instagram      = "https://www.instagram.com/sci_mate/"
  
  #[[params.friend_link]]
  #title = "Linda的博客"
  #href =  "https://zhaozhihan.com"

  #[[params.bookmark_link]]
  #title =  "Martin Fowler"
  #href =  "https://martinfowler.com"
  #[[params.bookmark_link]]
  #title = "ServiceMesher"
  #href =  "http://www.servicemesher.com"
  #[[params.bookmark_link]]
  #title =  "Pxhere"
  #href = "https://pxhere.com"
  #[[params.bookmark_link]]
  #title = "unsplash"
  #href = "https://unsplash.com"
  
  #[[params.addtional_menus]]
  #title =  "BOOKS"
  #href =  "/top/books/"

  [[params.addtional_menus]]
  title =  "ABOUT"
  href =  "/top/about/"

#[outputFormats.Algolia]
#baseName = "algolia"
#isPlainText = true
#mediaType = "application/json"
#notAlternative = true

#[params.algolia]
#vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
#params = ["categories", "tags"] 

[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1
  [markup.highlight]
    style = "dracula"
